Repository A-L-P-s/alps-ui, pull requests merged in 2023-05, with the labels that each got.

#21 setup: Add sample data for initial component build out
  src/sampleData/feedback.tsx
  src/sampleData/prompt.tsx
  src/sampleData/user.tsx
  src/sampleData/users.tsx
Labels: setup

#23 FE | Feature/form components
  src/assets/info_icon.svg
  src/components/Feedback/Feedback.css
  src/components/Feedback/Feedback.tsx
  src/components/Form/Form.css
  src/components/Form/Form.tsx
  src/components/Instructions/Instructions.tsx
  src/sampleData/feedback.tsx
  src/sampleData/prompt.tsx
Labels: setup

#25 Feature/user api calls
  src/api-calls.tsx
Labels: setup

#34 feat: Setup Link components in Form and Feedback
  src/components/App/App.tsx
  src/components/Feedback/Feedback.tsx
  src/components/Form/Form.tsx
Labels: enhancement

#42 Feature/get prompt
  src/Utilities/api-calls.tsx
  src/Utilities/interfaces.tsx
  src/components/Form/Form.tsx
  src/index.tsx
Labels: enhancement

#44 refac: Update feedback to account for AI explanation
  src/Utilities/interfaces.tsx
  src/components/Feedback/Feedback.tsx
  src/sampleData/feedback.tsx
Labels: refactor

#58 Feature/submit form
  src/Utilities/api-calls.tsx
  src/Utilities/interfaces.tsx
  src/components/App/App.tsx
  src/components/Dashboard/Dashboard.tsx
  src/components/Form/Form.tsx
  src/components/Header/Header.tsx
Labels: enhancement

#59 Feature/react modal
  package-lock.json
  package.json
  src/components/Form/Form.css
  src/components/Form/Form.tsx
Labels: enhancement

#63 Feature/feedback hookup
  src/Utilities/api-calls.tsx
  src/Utilities/interfaces.tsx
  src/components/App/App.css
  src/components/App/App.tsx
  src/components/ChallengeCard/ChallengeCard.tsx
  src/components/Dashboard/Dashboard.tsx
  src/components/Feedback/Feedback.tsx
  src/components/Form/Form.tsx
  src/components/PastChallenges/PastChallenges.tsx
Labels: enhancement, fix

#66 Feature/error handling 2
  package-lock.json
  package.json
  src/Utilities/api-calls.tsx
  src/components/App/App.tsx
  src/components/ChallengeCard/ChallengeCard.tsx
  src/components/Dashboard/Dashboard.tsx
  src/components/Feedback/Feedback.tsx
  src/components/Form/Form.tsx
  src/components/Header/Header.tsx
  src/components/Home/Home.tsx
  src/components/Instructions/Instructions.tsx
  src/components/Loading/Loading.css
  src/components/Loading/Loading.tsx
  src/components/NotFound/NotFound.css
  src/components/NotFound/NotFound.tsx
  src/components/PastChallenges/PastChallenges.tsx
  src/components/User/User.tsx
Labels: enhancement

#69 Setup/cypress intercepts
  cypress/e2e/spec.cy.ts
  cypress/fixtures/example.json
  cypress/fixtures/mock_dashboard_1.json
  cypress/fixtures/mock_dashboard_55.json
  cypress/fixtures/mock_past_feedback_1_1.json
  cypress/fixtures/mock_past_feedback_55_3.json
  cypress/fixtures/mock_prompt_1.json
  cypress/fixtures/mock_prompt_55.json
  cypress/fixtures/mock_submission_feedback_1.json
  cypress/fixtures/mock_submission_feedback_55.json
  cypress/fixtures/mock_users.json
  cypress/support/commands.ts
Labels: setup

#71 Feature/input field character limit
  src/components/Form/Form.tsx
Labels: enhancement

#75 feat: Test Deniz and Alexis dashboard navigation
  cypress/e2e/dashboard_spec.cy.ts
  cypress/fixtures/mock_dashboard_55.json
Labels: enhancement

#78 Styling/css updates
  cypress/e2e/dashboard_spec.cy.ts
  cypress/fixtures/mock_users.json
  cypress/support/commands.ts
  public/index.html
  src/assets/dog.png
  src/assets/logo.png
  src/assets/panda.png
  src/components/App/App.css
  src/components/App/App.tsx
  src/components/ChallengeCard/ChallengeCard.css
  src/components/Dashboard/Dashboard.css
  src/components/Feedback/Feedback.css
  src/components/Feedback/Feedback.tsx
  src/components/Form/Form.css
  src/components/Form/Form.tsx
  src/components/Header/Header.css
  src/components/Header/Header.tsx
  src/components/Home/Home.css
  src/components/Home/Home.tsx
  src/components/Loading/Loading.tsx
  src/components/NotFound/NotFound.css
  src/components/NotFound/NotFound.tsx
  src/components/PastChallenges/PastChallenges.css
  src/components/User/User.css
  src/components/User/User.tsx
Labels: enhancement

#81 refac: Add ITruncUserData interface to match new JSON contract
  src/Utilities/interfaces.tsx
  src/components/Form/Form.tsx
Labels: refactor

#89 Testing/test submission flow
  cypress/e2e/submission_spec.cy.ts
  cypress/fixtures/posted_mock_dashboard_1.json
  src/assets/koala.png
  src/components/App/App.tsx
  src/components/Feedback/Feedback.tsx
  src/components/NotFound/NotFound.css
  src/components/NotFound/NotFound.tsx
  src/components/User/User.css
  src/components/User/User.tsx
Labels: testing

#93 feat: Add 404 html file
  cypress/e2e/dashboard_spec.cy.ts
  public/404.html
  src/components/App/App.tsx
Labels: fix

#94 Cypress/sad paths
  cypress/e2e/sad_paths_spec.cy.ts
  cypress/e2e/spec.cy.ts
  cypress/e2e/submission_spec.cy.ts
Labels: testing

#95 fix: Delete 404.html file
  public/404.html
Labels: fix

#97 Styling/responsive
  cypress/e2e/dashboard_spec.cy.ts
  cypress/e2e/feedback_spec.cy.ts
  cypress/e2e/instructions_spec.cy.ts
  cypress/e2e/sad_paths_spec.cy.ts
  cypress/e2e/submission_spec.cy.ts
  src/components/App/App.css
  src/components/ChallengeCard/ChallengeCard.css
  src/components/ChallengeCard/ChallengeCard.tsx
  src/components/Dashboard/Dashboard.css
  src/components/Feedback/Feedback.css
  src/components/Feedback/Feedback.tsx
  src/components/Form/Form.css
  src/components/Header/Header.css
  src/components/Home/Home.css
  src/components/Instructions/Instructions.tsx
  src/components/PastChallenges/PastChallenges.css
  src/components/User/User.css
  src/index.css
Labels: refactor, styling, testing

#98 Docs/update readme
  README.md
  src/Utilities/api-calls.tsx
  src/assets/dashboard-wireframe.png
  src/assets/feedback-wireframe.png
  src/assets/home-wireframe.png
  src/assets/koala.png
  src/assets/prompt-wireframe.png
  src/components/App/App.css
  src/components/App/App.tsx
  src/components/ChallengeCard/ChallengeCard.css
  src/components/Dashboard/Dashboard.css
  src/components/Feedback/Feedback.css
  src/components/Feedback/Feedback.tsx
  src/components/Form/Form.css
  src/components/Form/Form.tsx
  src/components/Header/Header.css
  src/components/Home/Home.tsx
  src/components/Instructions/Instructions.css
  src/components/Instructions/Instructions.tsx
  src/components/PastChallenges/PastChallenges.css
  src/components/User/User.tsx
  src/sampleData/feedback.tsx
  src/sampleData/prompt.tsx
  src/sampleData/user.tsx
  src/sampleData/users.tsx
Labels: documentation, refactor

#99 style: Adjust feedback 2 sentence font
  src/components/Feedback/Feedback.tsx
Labels: refactor, styling

#102 docs: Add images and project gif to Readme
  README.md
  src/assets/bea.png
  src/assets/brian.jpg
  src/assets/caleb.jpg
  src/assets/david.jpg
  src/assets/huy.jpg
  src/assets/james.jpg
  src/assets/katherine.jpg
  src/assets/kirk.jpg
  src/assets/mel.jpg
  src/assets/taylor.jpg
Labels: documentation

#103 refac: Minor refactoring for readme
  README.md
Labels: documentation, refactor

#104 feat: Update API calls with AWS server endpoints
  cypress/e2e/submission_spec.cy.ts
  cypress/support/commands.ts
  src/Utilities/api-calls.tsx
Labels: enhancement
